services:
  detailing-crm-frontend-develop:
    image: ${ENV_DETAILING_CRM_FRONTEND_IMAGE}
    container_name: ${DETAILING_CRM_FRONTEND_CONTAINER_NAME}
    ports:
      - '80:80'

    restart: always
    networks:
      - network


networks:
  network:
    name: ${ENV_NETWORK}
    external: true

