services:
  detailing-crm-frontend-develop:
    image: ${ENV_DETAILING_CRM_FRONTEND_IMAGE}
    ports:
      - '80:80'

    restart: always
    networks:
      - ${ENV_NETWORK}


networks:
  ${ENV_NETWORK}:
    external: true
